name: Deploy lambda function
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Use .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Build and pack
      run: |
        dotnet pack --configuration Release -p:PackageVersion=${{ env.RELEASE_VERSION }} --output out

    - name: Nuget push
      run: |
        dotnet nuget push .\out\*.nupkg --api-key ${{NUGET_API_KEY}}