name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.402

    - name: Build and pack
      run: |
        dotnet build --configuration Release
