name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Build and pack
      run: |
        dotnet build --configuration Release

