name: Publish nuget by repository tag
on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Check output
      run: |
          echo ${{ steps.vars.outputs.tag }}

    - name: Use .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Build and pack
      run: |
        dotnet pack --configuration Release -p:PackageVersion=${{ steps.vars.outputs.tag }} --output out

    - name: Nuget push
      run: |
        dotnet nuget push ./out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}